# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17kyTIXsSjQNY04tclrGcDb0kkpb_HYdE
"""

pip install experta

pip install --upgrade frozendict

from experta import *

class Diagnosis(KnowledgeEngine):
    @Rule(Fact(daun_menguning=True) & Fact(bercak_hitam=True)& Fact(tanaman_layu=False))
    def penyakit1(self):
      print("sepertinya tanaman anda terkena penyakit hawar daun")

    @Rule(Fact(daun_menguning=True) & Fact(tanaman_layu=True)&Fact(bercak_hitam=False))
    def penyakit2(self):
      print("sepertinya tanaman anda terserang bakteri fusarium")


    @Rule(Fact(bercak_hitam=True) & Fact(tanaman_layu=True)&Fact(daun_menguning=False))
    def penyakit3(self):
      print("tanaman anda terjangkit antraknosa")

    @Rule(Fact(daun_menguning=False) & Fact(tanaman_layu=False)&Fact(daun_berlubang=False)&Fact(bercak_hitam=False))
    def healty(self):
      print("tanaman anda sehat")

    @Rule(AS.f << Fact(), salience=-10)
    def default_diagnosis(self):
        print("Gejala yang terdeteksi tidak cocok dengan data yang ada. Silakan periksa kembali atau konsultasikan lebih lanjut.")



def get_input():
    """Helper function to get user input as boolean (yes/no)."""
    def ask_question(question):
      return input(question + "(yes/no):").strip().lower()=="yes"

    return {
      "bercak_hitam": ask_question("Apakah tanaman anda memiliki bercak hitam?"),
      "daun_menguning": ask_question("Apakah tanaman anda daunnya tampak menguning?"),
      "daun_berlubang": ask_question("Apakah tanaman anda memiliki daun berlubang?"),
      "tanaman_layu": ask_question("Apakah tanaman anda layu?")
    }


if __name__ == "__main__":
  symptoms = get_input()
  engine = Diagnosis()
  engine.reset()

  for symptom,present in symptoms.items():
    engine.declare(Fact(**{symptom:present}))

  engine.run()